language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t rabelais/stph-react-test -f ./client/!dev.Dockerfile ./client

script:
  - docker run -e CI=true rabelais/stph-react-test npm test -- --coverage

after_success:
  - docker build -t rabelais/stph-react-test -f ./client/!prod.Dockerfile ./client